#!/bin/bash

echo WELCOME TO CIV13:OSE!
echo MAKE SURE YOU RUN THIS COMMAND AS SUDO
echo -----------------
echo Prepairing the system...
sudo dpkg --add-architecture i386
sudo apt update
sudo apt upgrade
echo Checking Dependancies.... 
sudo apt install python3 wget git unzip make sudo
echo ...Installed!
sudo rm INSTALL-LINUX.py
sudo wget https://raw.githubusercontent.com/DojoDetroit/Civ13/master/INSTALL-LINUX.py
sudo python3 INSTALL-LINUX.py 513 1525